name: alioss-update-auto
env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: "0 20 * * sun" # 时区对cron无效，所以要提前8个小时，
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Init Action
        run: |
          sudo apt install -y certbot
          pip install -r requirements.txt

      - name: Aliyun Cli Tools
        run: |
          curl -o aliyun-cli.tgz https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
          tar xzvf aliyun-cli.tgz
          sudo mv aliyun /usr/local/bin/
          sudo aliyun configure set --profile akProfile --mode AK \
            --access-key-id ${{ secrets.ACCESS_KEY_ID }} \
            --access-key-secret ${{ secrets.ACCESS_KEY_SECRET }} \
            --region ${{ secrets.REGION }}

          sudo mv alidns.sh /usr/local/bin/alidns
          sudo chmod +x /usr/local/bin/alidns

      - name: Apply for a new certificate
        run: |
          sudo mkdir -p /etc/letsencrypt/certs
          sudo certbot certonly -d "${{ secrets.DOMAIN }}" --manual --preferred-challenges dns \
                --manual-auth-hook "/usr/local/bin/alidns" \
                --manual-cleanup-hook "/usr/local/bin/alidns clean" \
                --agree-tos --email ${{ secrets.EMAIL }} --non-interactive

      - name: Run OSS Cert Update
        run: |
          CERT_PATH="/etc/letsencrypt/live/${{ secrets.DOMAIN }}"
          export CERTIFICATE="$(sudo cat $CERT_PATH/fullchain.pem)"
          export PRIVATE_KEY="$(sudo cat $CERT_PATH/privkey.pem)"
          python oss_update.py \
            --access-key-id "${{ secrets.ACCESS_KEY_ID }}" \
            --access-key-secret "${{ secrets.ACCESS_KEY_SECRET }}" \
            --endpoint "${{ secrets.ENDPOINT }}" \
            --bucket-name "${{ secrets.BUCKET_NAME }}" \
            --target-cname "${{ secrets.DOMAIN }}" \
            --private-key "$PRIVATE_KEY" \
            --certificate "$CERTIFICATE"